services:
  - type: web
    name: stdavdan-ngo-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: https://stdavdan.org
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://stdavdan.org
