services:
  - type: web
    name: stdavdan-ngo-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://stdavdan.org
      - key: PRODUCTION_URL
        value: https://stdavdan.org
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://stdavdan.org
